### ISSUE TITLE
conn.disconnect() crashes Nodejs

### ISSUE THREAD

**Issue by LexDias** [sqlanywhere/node-sqlanywhere#19]
This problem occurs on v1.0.10 and it was explained before at [this issue](https://github.com/sqlanywhere/node-sqlanywhere/issues/15). 

It was corrected on v.1.0.11.

I've downloaded v.1.0.12 and the problem mentioned at returned. Any ideas?

**Comment by gperrow-SAP** [comment]
It's a different issue but the same result. We are crashing because you are calling the disconnect method inside the callback from exec. This is a perfectly valid thing to do but we're not handling it well. In addition, the automated tests I wrote to check for this were incomplete. Until I get a fix in place, you can put the conn.disconnect() inside a call to process.nextTick() and that will clean it up.

**Comment by gperrow-SAP** [comment]
This is fixed in v1.0.13.

**Comment by LexDias** [comment]
Worked fine! Thanks a lot!
